--
-- create model tables: OzProjX
-- model digest:        2e697e28ca63b708a198849eee824e3f
-- script created:      2025-06-01 18:50:48.692
--

--
-- create model input parameters
--
CREATE TABLE IF NOT EXISTS ArrivalRegionDistn_p1b1d674f (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (run_id, sub_id, dim0, dim1, dim2));
CREATE TABLE IF NOT EXISTS ArrivalRegionDistn_w1b1d674f (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (set_id, sub_id, dim0, dim1, dim2));
CREATE TABLE IF NOT EXISTS DestinationDist_pf6d0f72c (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (run_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS DestinationDist_wf6d0f72c (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (set_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS EmigrationRate_p780b1286 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (run_id, sub_id, dim0, dim1, dim2));
CREATE TABLE IF NOT EXISTS EmigrationRate_w780b1286 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (set_id, sub_id, dim0, dim1, dim2));
CREATE TABLE IF NOT EXISTS FertilityRate_pdda6ef40 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (run_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS FertilityRate_wdda6ef40 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (set_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS Immigrants_pbf3a7fb9 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, param_value INT NOT NULL, PRIMARY KEY (run_id, sub_id, dim0));
CREATE TABLE IF NOT EXISTS Immigrants_wbf3a7fb9 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, param_value INT NOT NULL, PRIMARY KEY (set_id, sub_id, dim0));
CREATE TABLE IF NOT EXISTS MathMomentHazard_p1d09ba40 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS MathMomentHazard_w1d09ba40 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS MathMomentPrimesToCalculate_p237edbcd (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value INT NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS MathMomentPrimesToCalculate_w237edbcd (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value INT NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS MaxYearsForImmigrantDonor_p99032d1f (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value INT NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS MaxYearsForImmigrantDonor_w99032d1f (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value INT NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS MicroDataInPieces_pba0a426d (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value SMALLINT NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS MicroDataInPieces_wba0a426d (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value SMALLINT NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS MicroDataInputFile_p7d40b028 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value VARCHAR(260) NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS MicroDataInputFile_w7d40b028 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value VARCHAR(260) NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS MicroDataOutputFile_p6d28ab86 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value VARCHAR(260) NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS MicroDataOutputFile_w6d28ab86 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value VARCHAR(260) NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS MicroDataOutputFlag_p1c00c4b4 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value SMALLINT NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS MicroDataOutputFlag_w1c00c4b4 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value SMALLINT NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS MicroDataOutputTime_pf12171c1 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS MicroDataOutputTime_wf12171c1 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS MortalityRate_p1c686222 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (run_id, sub_id, dim0, dim1, dim2));
CREATE TABLE IF NOT EXISTS MortalityRate_w1c686222 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (set_id, sub_id, dim0, dim1, dim2));
CREATE TABLE IF NOT EXISTS NativeToIndigenous_peb896ad5 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS NativeToIndigenous_web896ad5 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS OutMigrationRate_pda90d112 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (run_id, sub_id, dim0, dim1, dim2));
CREATE TABLE IF NOT EXISTS OutMigrationRate_wda90d112 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (set_id, sub_id, dim0, dim1, dim2));
CREATE TABLE IF NOT EXISTS RealWorldStartPopulation_p44922698 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value INT NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS RealWorldStartPopulation_w44922698 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value INT NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS RelativeFertilityIndigenous_pc9d4d4d2 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (run_id, sub_id, dim0));
CREATE TABLE IF NOT EXISTS RelativeFertilityIndigenous_wc9d4d4d2 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (set_id, sub_id, dim0));
CREATE TABLE IF NOT EXISTS SexRatioAtBirth_pa947c82d (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS SexRatioAtBirth_wa947c82d (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS SimulationCases_p8b4bccb7 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value BIGINT NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS SimulationCases_w8b4bccb7 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value BIGINT NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS SimulationSeed_p3df984c3 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value BIGINT NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS SimulationSeed_w3df984c3 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value BIGINT NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS SimulationStartTime_p1c304b48 (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (run_id, sub_id));
CREATE TABLE IF NOT EXISTS SimulationStartTime_w1c304b48 (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (set_id, sub_id));
CREATE TABLE IF NOT EXISTS UndercountRate_p2387e82a (run_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (run_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS UndercountRate_w2387e82a (set_id INT NOT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, param_value FLOAT NOT NULL, PRIMARY KEY (set_id, sub_id, dim0, dim1));

--
-- create model output tables and views
--
CREATE TABLE IF NOT EXISTS BirthsByYear_a6a87a9a9 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0));
CREATE TABLE IF NOT EXISTS BirthsByYear_v6a87a9a9 (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0));
CREATE VIEW IF NOT EXISTS BirthsByYear_d6a87a9a9 AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM BirthsByYear_a6a87a9a9 A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS DeathsByAgeSex_ac9ba97b5 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS DeathsByAgeSex_vc9ba97b5 (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL, dim1 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0, dim1));
CREATE VIEW IF NOT EXISTS DeathsByAgeSex_dc9ba97b5 AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.dim1 AS "Dim1", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM DeathsByAgeSex_ac9ba97b5 A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS DeparturesByYear_a5ce5e506 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0));
CREATE TABLE IF NOT EXISTS DeparturesByYear_v5ce5e506 (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0));
CREATE VIEW IF NOT EXISTS DeparturesByYear_d5ce5e506 AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM DeparturesByYear_a5ce5e506 A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS Experiment1_afb8d750b (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0));
CREATE TABLE IF NOT EXISTS Experiment1_vfb8d750b (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0));
CREATE VIEW IF NOT EXISTS Experiment1_dfb8d750b AS WITH va1 AS (SELECT run_id, sub_id, dim0, acc_value FROM Experiment1_afb8d750b WHERE acc_id = 1), va2 AS (SELECT run_id, sub_id, dim0, acc_value FROM Experiment1_afb8d750b WHERE acc_id = 2), va3 AS (SELECT run_id, sub_id, dim0, acc_value FROM Experiment1_afb8d750b WHERE acc_id = 3), va4 AS (SELECT run_id, sub_id, dim0, acc_value FROM Experiment1_afb8d750b WHERE acc_id = 4) SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.acc_value AS "acc0", A1.acc_value AS "acc1", A2.acc_value AS "acc2", A3.acc_value AS "acc3", A4.acc_value AS "acc4", ( A.acc_value ) AS "Expr0", ( A1.acc_value ) AS "Expr1", ( A2.acc_value ) AS "Expr2", ( A3.acc_value ) AS "Expr3", ( A4.acc_value ) AS "Expr4", ( A4.acc_value ) AS "Expr5" FROM Experiment1_afb8d750b A INNER JOIN va1 A1 ON (A1.run_id = A.run_id AND A1.sub_id = A.sub_id AND A1.dim0 = A.dim0) INNER JOIN va2 A2 ON (A2.run_id = A.run_id AND A2.sub_id = A.sub_id AND A2.dim0 = A.dim0) INNER JOIN va3 A3 ON (A3.run_id = A.run_id AND A3.sub_id = A.sub_id AND A3.dim0 = A.dim0) INNER JOIN va4 A4 ON (A4.run_id = A.run_id AND A4.sub_id = A.sub_id AND A4.dim0 = A.dim0) WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS Experiment2_abe3df0bc (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0));
CREATE TABLE IF NOT EXISTS Experiment2_vbe3df0bc (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0));
CREATE VIEW IF NOT EXISTS Experiment2_dbe3df0bc AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM Experiment2_abe3df0bc A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS Experiment3_a522d153a (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS Experiment3_v522d153a (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL, dim1 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0, dim1));
CREATE VIEW IF NOT EXISTS Experiment3_d522d153a AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.dim1 AS "Dim1", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM Experiment3_a522d153a A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS Experiment4_a2ff235db (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS Experiment4_v2ff235db (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL, dim1 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0, dim1));
CREATE VIEW IF NOT EXISTS Experiment4_d2ff235db AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.dim1 AS "Dim1", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM Experiment4_a2ff235db A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS Experiment5_a5cffa0fd (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS Experiment5_v5cffa0fd (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL, dim1 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0, dim1));
CREATE VIEW IF NOT EXISTS Experiment5_d5cffa0fd AS WITH va1 AS (SELECT run_id, sub_id, dim0, dim1, acc_value FROM Experiment5_a5cffa0fd WHERE acc_id = 1) SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.dim1 AS "Dim1", A.acc_value AS "acc0", A1.acc_value AS "acc1", ( (A.acc_value / A1.acc_value) ) AS "Expr0" FROM Experiment5_a5cffa0fd A INNER JOIN va1 A1 ON (A1.run_id = A.run_id AND A1.sub_id = A.sub_id AND A1.dim0 = A.dim0 AND A1.dim1 = A.dim1) WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS Experiment6_a3b291b2f (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS Experiment6_v3b291b2f (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL, dim1 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0, dim1));
CREATE VIEW IF NOT EXISTS Experiment6_d3b291b2f AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.dim1 AS "Dim1", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM Experiment6_a3b291b2f A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS InitialPopCounts_ac107a6da (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS InitialPopCounts_vc107a6da (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL, dim1 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0, dim1));
CREATE VIEW IF NOT EXISTS InitialPopCounts_dc107a6da AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.dim1 AS "Dim1", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM InitialPopCounts_ac107a6da A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS MathMoments_af883e5ce (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id));
CREATE TABLE IF NOT EXISTS MathMoments_vf883e5ce (run_id INT NOT NULL, expr_id SMALLINT NULL, expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id));
CREATE VIEW IF NOT EXISTS MathMoments_df883e5ce AS WITH va1 AS (SELECT run_id, sub_id, acc_value FROM MathMoments_af883e5ce WHERE acc_id = 1) SELECT A.run_id, A.sub_id, A.acc_value AS "acc0", A1.acc_value AS "acc1", ( A.acc_value ) AS "math_moments", ( A1.acc_value ) AS "primes_found" FROM MathMoments_af883e5ce A INNER JOIN va1 A1 ON (A1.run_id = A.run_id AND A1.sub_id = A.sub_id) WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS MicrodataAge_a5e604d10 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0));
CREATE TABLE IF NOT EXISTS MicrodataAge_v5e604d10 (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0));
CREATE VIEW IF NOT EXISTS MicrodataAge_d5e604d10 AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM MicrodataAge_a5e604d10 A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS MicrodataIndigenous_aa5f660a9 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS MicrodataIndigenous_va5f660a9 (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL, dim1 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0, dim1));
CREATE VIEW IF NOT EXISTS MicrodataIndigenous_da5f660a9 AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.dim1 AS "Dim1", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM MicrodataIndigenous_aa5f660a9 A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS MicrodataNativeBorn_af5339edc (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0));
CREATE TABLE IF NOT EXISTS MicrodataNativeBorn_vf5339edc (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0));
CREATE VIEW IF NOT EXISTS MicrodataNativeBorn_df5339edc AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM MicrodataNativeBorn_af5339edc A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS MicrodataRecentArrival_a7c8d6e13 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0));
CREATE TABLE IF NOT EXISTS MicrodataRecentArrival_v7c8d6e13 (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0));
CREATE VIEW IF NOT EXISTS MicrodataRecentArrival_d7c8d6e13 AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM MicrodataRecentArrival_a7c8d6e13 A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS MicrodataRegion_a12a57f25 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS MicrodataRegion_v12a57f25 (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL, dim1 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0, dim1));
CREATE VIEW IF NOT EXISTS MicrodataRegion_d12a57f25 AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.dim1 AS "Dim1", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM MicrodataRegion_a12a57f25 A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS MicrodataSex_a6a27dfb3 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0));
CREATE TABLE IF NOT EXISTS MicrodataSex_v6a27dfb3 (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0));
CREATE VIEW IF NOT EXISTS MicrodataSex_d6a27dfb3 AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM MicrodataSex_a6a27dfb3 A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS MicrodataYearsSinceArrival_a6c9377fd (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0));
CREATE TABLE IF NOT EXISTS MicrodataYearsSinceArrival_v6c9377fd (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0));
CREATE VIEW IF NOT EXISTS MicrodataYearsSinceArrival_d6c9377fd AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM MicrodataYearsSinceArrival_a6c9377fd A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS MigrantsByOriginAndDestination_ac023f407 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS MigrantsByOriginAndDestination_vc023f407 (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL, dim1 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0, dim1));
CREATE VIEW IF NOT EXISTS MigrantsByOriginAndDestination_dc023f407 AS WITH va1 AS (SELECT run_id, sub_id, dim0, dim1, acc_value FROM MigrantsByOriginAndDestination_ac023f407 WHERE acc_id = 1), va2 AS (SELECT run_id, sub_id, dim0, dim1, acc_value FROM MigrantsByOriginAndDestination_ac023f407 WHERE acc_id = 2), va3 AS (SELECT run_id, sub_id, dim0, dim1, acc_value FROM MigrantsByOriginAndDestination_ac023f407 WHERE acc_id = 3), va4 AS (SELECT run_id, sub_id, dim0, dim1, acc_value FROM MigrantsByOriginAndDestination_ac023f407 WHERE acc_id = 4), va5 AS (SELECT run_id, sub_id, dim0, dim1, acc_value FROM MigrantsByOriginAndDestination_ac023f407 WHERE acc_id = 5), va6 AS (SELECT run_id, sub_id, dim0, dim1, acc_value FROM MigrantsByOriginAndDestination_ac023f407 WHERE acc_id = 6), va7 AS (SELECT run_id, sub_id, dim0, dim1, acc_value FROM MigrantsByOriginAndDestination_ac023f407 WHERE acc_id = 7) SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.dim1 AS "Dim1", A.acc_value AS "acc0", A1.acc_value AS "acc1", A2.acc_value AS "acc2", A3.acc_value AS "acc3", A4.acc_value AS "acc4", A5.acc_value AS "acc5", A6.acc_value AS "acc6", A7.acc_value AS "acc7", ( A.acc_value ) AS "Expr0", ( A1.acc_value ) AS "Expr1", ( A2.acc_value ) AS "Expr2", ( A3.acc_value ) AS "Expr3", ( A4.acc_value ) AS "Expr4", ( A5.acc_value ) AS "Expr5", ( A6.acc_value ) AS "Expr6", ( A7.acc_value ) AS "Expr7" FROM MigrantsByOriginAndDestination_ac023f407 A INNER JOIN va1 A1 ON (A1.run_id = A.run_id AND A1.sub_id = A.sub_id AND A1.dim0 = A.dim0 AND A1.dim1 = A.dim1) INNER JOIN va2 A2 ON (A2.run_id = A.run_id AND A2.sub_id = A.sub_id AND A2.dim0 = A.dim0 AND A2.dim1 = A.dim1) INNER JOIN va3 A3 ON (A3.run_id = A.run_id AND A3.sub_id = A.sub_id AND A3.dim0 = A.dim0 AND A3.dim1 = A.dim1) INNER JOIN va4 A4 ON (A4.run_id = A.run_id AND A4.sub_id = A.sub_id AND A4.dim0 = A.dim0 AND A4.dim1 = A.dim1) INNER JOIN va5 A5 ON (A5.run_id = A.run_id AND A5.sub_id = A.sub_id AND A5.dim0 = A.dim0 AND A5.dim1 = A.dim1) INNER JOIN va6 A6 ON (A6.run_id = A.run_id AND A6.sub_id = A.sub_id AND A6.dim0 = A.dim0 AND A6.dim1 = A.dim1) INNER JOIN va7 A7 ON (A7.run_id = A.run_id AND A7.sub_id = A.sub_id AND A7.dim0 = A.dim0 AND A7.dim1 = A.dim1) WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS PersonYearsLived_ac97b5075 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0, dim1, dim2));
CREATE TABLE IF NOT EXISTS PersonYearsLived_vc97b5075 (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0, dim1, dim2));
CREATE VIEW IF NOT EXISTS PersonYearsLived_dc97b5075 AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.dim1 AS "Dim1", A.dim2 AS "Dim2", A.acc_value AS "acc0", ( A.acc_value ) AS "Expr0" FROM PersonYearsLived_ac97b5075 A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS EmigrationHazard_aba1714c2 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0, dim1, dim2));
CREATE TABLE IF NOT EXISTS EmigrationHazard_vba1714c2 (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0, dim1, dim2));
CREATE VIEW IF NOT EXISTS EmigrationHazard_dba1714c2 AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.dim1 AS "Dim1", A.dim2 AS "Dim2", A.acc_value AS "acc0" FROM EmigrationHazard_aba1714c2 A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS FertilityHazard_a48da2cb6 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0, dim1));
CREATE TABLE IF NOT EXISTS FertilityHazard_v48da2cb6 (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL, dim1 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0, dim1));
CREATE VIEW IF NOT EXISTS FertilityHazard_d48da2cb6 AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.dim1 AS "Dim1", A.acc_value AS "acc0" FROM FertilityHazard_a48da2cb6 A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS ImmigrantDonors_a13fc62b8 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id));
CREATE TABLE IF NOT EXISTS ImmigrantDonors_v13fc62b8 (run_id INT NOT NULL, expr_id SMALLINT NULL, expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id));
CREATE VIEW IF NOT EXISTS ImmigrantDonors_d13fc62b8 AS  SELECT A.run_id, A.sub_id, A.acc_value AS "acc0" FROM ImmigrantDonors_a13fc62b8 A WHERE A.acc_id = 0;
CREATE TABLE IF NOT EXISTS MortalityHazard_af84bc967 (run_id INT NOT NULL, acc_id SMALLINT NULL, sub_id SMALLINT NOT NULL, dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL, acc_value FLOAT NULL, PRIMARY KEY (run_id, acc_id, sub_id, dim0, dim1, dim2));
CREATE TABLE IF NOT EXISTS MortalityHazard_vf84bc967 (run_id INT NOT NULL, expr_id SMALLINT NULL,dim0 INT NOT NULL, dim1 INT NOT NULL, dim2 INT NOT NULL,  expr_value FLOAT NULL, PRIMARY KEY (run_id, expr_id, dim0, dim1, dim2));
CREATE VIEW IF NOT EXISTS MortalityHazard_df84bc967 AS  SELECT A.run_id, A.sub_id, A.dim0 AS "Dim0", A.dim1 AS "Dim1", A.dim2 AS "Dim2", A.acc_value AS "acc0" FROM MortalityHazard_af84bc967 A WHERE A.acc_id = 0;

