--
-- compatibility views for model: OzProjX
-- model digest:   2e697e28ca63b708a198849eee824e3f
-- script created: 2025-06-01 18:50:48.692
--
-- Dear user:
--   this part of database is optional and NOT used by openM++
--   if you want it for any reason please enjoy else just ignore it
-- Or other words:
--   if you don't know what this is then you don't need it
--

--
-- input parameters compatibility views
--
CREATE VIEW IF NOT EXISTS ArrivalRegionDistn AS SELECT S.dim0 AS "Dim0", S.dim1 AS "Dim1", S.dim2 AS "Dim2", S.param_value AS "Value" FROM ArrivalRegionDistn_p1b1d674f S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS DestinationDist AS SELECT S.dim0 AS "Dim0", S.dim1 AS "Dim1", S.param_value AS "Value" FROM DestinationDist_pf6d0f72c S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS EmigrationRate AS SELECT S.dim0 AS "Dim0", S.dim1 AS "Dim1", (S.dim2 - 2012) AS "Dim2", S.param_value AS "Value" FROM EmigrationRate_p780b1286 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS FertilityRate AS SELECT (S.dim0 - 15) AS "Dim0", (S.dim1 - 2012) AS "Dim1", S.param_value AS "Value" FROM FertilityRate_pdda6ef40 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS Immigrants AS SELECT (S.dim0 - 2012) AS "Dim0", S.param_value AS "Value" FROM Immigrants_pbf3a7fb9 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MathMomentHazard AS SELECT S.param_value AS "Value" FROM MathMomentHazard_p1d09ba40 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MathMomentPrimesToCalculate AS SELECT S.param_value AS "Value" FROM MathMomentPrimesToCalculate_p237edbcd S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MaxYearsForImmigrantDonor AS SELECT S.param_value AS "Value" FROM MaxYearsForImmigrantDonor_p99032d1f S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MicroDataInPieces AS SELECT S.param_value AS "Value" FROM MicroDataInPieces_pba0a426d S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MicroDataInputFile AS SELECT S.param_value AS "Value" FROM MicroDataInputFile_p7d40b028 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MicroDataOutputFile AS SELECT S.param_value AS "Value" FROM MicroDataOutputFile_p6d28ab86 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MicroDataOutputFlag AS SELECT S.param_value AS "Value" FROM MicroDataOutputFlag_p1c00c4b4 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MicroDataOutputTime AS SELECT S.param_value AS "Value" FROM MicroDataOutputTime_pf12171c1 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MortalityRate AS SELECT S.dim0 AS "Dim0", S.dim1 AS "Dim1", (S.dim2 - 2012) AS "Dim2", S.param_value AS "Value" FROM MortalityRate_p1c686222 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS NativeToIndigenous AS SELECT S.param_value AS "Value" FROM NativeToIndigenous_peb896ad5 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS OutMigrationRate AS SELECT S.dim0 AS "Dim0", S.dim1 AS "Dim1", S.dim2 AS "Dim2", S.param_value AS "Value" FROM OutMigrationRate_pda90d112 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS RealWorldStartPopulation AS SELECT S.param_value AS "Value" FROM RealWorldStartPopulation_p44922698 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS RelativeFertilityIndigenous AS SELECT (S.dim0 - 2012) AS "Dim0", S.param_value AS "Value" FROM RelativeFertilityIndigenous_pc9d4d4d2 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS SexRatioAtBirth AS SELECT S.param_value AS "Value" FROM SexRatioAtBirth_pa947c82d S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS SimulationCases AS SELECT S.param_value AS "Value" FROM SimulationCases_p8b4bccb7 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS SimulationSeed AS SELECT S.param_value AS "Value" FROM SimulationSeed_p3df984c3 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS SimulationStartTime AS SELECT S.param_value AS "Value" FROM SimulationStartTime_p1c304b48 S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS UndercountRate AS SELECT S.dim0 AS "Dim0", S.dim1 AS "Dim1", S.param_value AS "Value" FROM UndercountRate_p2387e82a S WHERE S.sub_id = 0 AND S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');

--
-- output tables compatibility views
--
CREATE VIEW IF NOT EXISTS BirthsByYear AS SELECT (S.dim0 - 2012) AS "Dim0", S.expr_id AS "Dim1", S.expr_value AS "Value" FROM BirthsByYear_v6a87a9a9 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS DeathsByAgeSex AS SELECT S.dim0 AS "Dim0", S.dim1 AS "Dim1", S.expr_id AS "Dim2", S.expr_value AS "Value" FROM DeathsByAgeSex_vc9ba97b5 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS DeparturesByYear AS SELECT (S.dim0 - 2012) AS "Dim0", S.expr_id AS "Dim1", S.expr_value AS "Value" FROM DeparturesByYear_v5ce5e506 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS Experiment1 AS SELECT S.dim0 AS "Dim0", S.expr_id AS "Dim1", S.expr_value AS "Value" FROM Experiment1_vfb8d750b S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS Experiment2 AS SELECT (S.dim0 - 2012) AS "Dim0", S.expr_id AS "Dim1", S.expr_value AS "Value" FROM Experiment2_vbe3df0bc S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS Experiment3 AS SELECT (S.dim0 - 2012) AS "Dim0", S.dim1 AS "Dim1", S.expr_id AS "Dim2", S.expr_value AS "Value" FROM Experiment3_v522d153a S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS Experiment4 AS SELECT (S.dim0 - 2012) AS "Dim0", S.dim1 AS "Dim1", S.expr_id AS "Dim2", S.expr_value AS "Value" FROM Experiment4_v2ff235db S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS Experiment5 AS SELECT (S.dim0 - 2012) AS "Dim0", S.dim1 AS "Dim1", S.expr_id AS "Dim2", S.expr_value AS "Value" FROM Experiment5_v5cffa0fd S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS Experiment6 AS SELECT (S.dim0 - 2012) AS "Dim0", S.dim1 AS "Dim1", S.expr_id AS "Dim2", S.expr_value AS "Value" FROM Experiment6_v3b291b2f S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS InitialPopCounts AS SELECT S.dim0 AS "Dim0", S.dim1 AS "Dim1", S.expr_id AS "Dim2", S.expr_value AS "Value" FROM InitialPopCounts_vc107a6da S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MathMoments AS SELECT S.expr_id AS "Dim0", S.expr_value AS "Value" FROM MathMoments_vf883e5ce S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MicrodataAge AS SELECT S.dim0 AS "Dim0", S.expr_id AS "Dim1", S.expr_value AS "Value" FROM MicrodataAge_v5e604d10 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MicrodataIndigenous AS SELECT S.dim0 AS "Dim0", S.dim1 AS "Dim1", S.expr_id AS "Dim2", S.expr_value AS "Value" FROM MicrodataIndigenous_va5f660a9 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MicrodataNativeBorn AS SELECT S.dim0 AS "Dim0", S.expr_id AS "Dim1", S.expr_value AS "Value" FROM MicrodataNativeBorn_vf5339edc S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MicrodataRecentArrival AS SELECT S.dim0 AS "Dim0", S.expr_id AS "Dim1", S.expr_value AS "Value" FROM MicrodataRecentArrival_v7c8d6e13 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MicrodataRegion AS SELECT S.dim0 AS "Dim0", S.dim1 AS "Dim1", S.expr_id AS "Dim2", S.expr_value AS "Value" FROM MicrodataRegion_v12a57f25 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MicrodataSex AS SELECT S.dim0 AS "Dim0", S.expr_id AS "Dim1", S.expr_value AS "Value" FROM MicrodataSex_v6a27dfb3 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MicrodataYearsSinceArrival AS SELECT S.dim0 AS "Dim0", S.expr_id AS "Dim1", S.expr_value AS "Value" FROM MicrodataYearsSinceArrival_v6c9377fd S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MigrantsByOriginAndDestination AS SELECT (S.dim0 - 2012) AS "Dim0", S.dim1 AS "Dim1", S.expr_id AS "Dim2", S.expr_value AS "Value" FROM MigrantsByOriginAndDestination_vc023f407 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS PersonYearsLived AS SELECT S.dim0 AS "Dim0", S.dim1 AS "Dim1", (S.dim2 - 2012) AS "Dim2", S.expr_id AS "Dim3", S.expr_value AS "Value" FROM PersonYearsLived_vc97b5075 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS EmigrationHazard AS SELECT S.dim0 AS "Dim0", S.dim1 AS "Dim1", (S.dim2 - 2012) AS "Dim2", S.expr_id AS "Dim3", S.expr_value AS "Value" FROM EmigrationHazard_vba1714c2 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS FertilityHazard AS SELECT (S.dim0 - 15) AS "Dim0", (S.dim1 - 2012) AS "Dim1", S.expr_id AS "Dim2", S.expr_value AS "Value" FROM FertilityHazard_v48da2cb6 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS ImmigrantDonors AS SELECT S.expr_id AS "Dim0", S.expr_value AS "Value" FROM ImmigrantDonors_v13fc62b8 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');
CREATE VIEW IF NOT EXISTS MortalityHazard AS SELECT S.dim0 AS "Dim0", S.dim1 AS "Dim1", (S.dim2 - 2012) AS "Dim2", S.expr_id AS "Dim3", S.expr_value AS "Value" FROM MortalityHazard_vf84bc967 S WHERE S.run_id = ( SELECT MIN(RL.run_id) FROM run_lst RL INNER JOIN model_dic M ON (M.model_id = RL.model_id) WHERE M.model_digest = '2e697e28ca63b708a198849eee824e3f');

