/**
 * Declarations for model 'RiskPaths' - Generated by openM++ compiler
 *  
 *  Model version = 3.0.0.0
 *  Model created = 2025-05-15 14:47:08.459
 *  Model digest = 2c0eef92573bbab8afa93e6eac19c1c9
 */

#pragma once

// PreSimulation, PostSimulation, UserTables functions in model source code

// weight support

extern thread_local double om_initial_weight;
extern thread_local double om_sum_weight;

/// set initial weight
void set_initial_weight(double w);

/// get initial weight
double get_initial_weight(void);

/// get sum of weights
double get_sum_weight(void);

/// reset weight API
void reset_weight(void);

// model scenario parameters

#ifdef OM_DEBUG_PARAMETERS


#else // OM_DEBUG_PARAMETERS


#endif // OM_DEBUG_PARAMETERS

// model parameters (fixed, derived, missing)


/// Parameter double: Age baseline for first union formation
extern const double AgeBaselineForm1[12];

/// Parameter double: Age baseline for first pregnancy
extern const double AgeBaselinePreg1[12];

/// Parameter bool: Switch mortality on/off
extern const bool CanDie;

/// Parameter double: Death probabilities
extern const double ProbMort[101];

/// Parameter double: Separation Duration Baseline of 2nd Formation
extern const double SeparationDurationBaseline[5];

/// Parameter llong: Number of cases in run (over all members)
extern const llong SimulationCases;

/// Parameter llong: Simulation starting seed
extern const llong SimulationSeed;

/// Parameter double: Union Duration Baseline of Dissolution
extern const double UnionDurationBaseline[2][6];

/// Parameter double: Relative risks of union status on first pregnancy
extern const double UnionStatusPreg1[6];


// entity tables
class cls_T01_LifeExpectancy final : public EntityTable<0, 1, 3, 2, false, false>
{
public:
    cls_T01_LifeExpectancy(const char* name, std::initializer_list<int> shape) : EntityTable<0, 1, 3, 2, false, false>(name, shape)
    {
    }
    void initialize_accumulators();
    void extract_accumulators();
    void scale_accumulators();
    void compute_expressions();
};
typedef cls_T01_LifeExpectancy T01_LifeExpectancy;
extern thread_local T01_LifeExpectancy * theT01_LifeExpectancy;

/// Count of increments pushed to table T01_LifeExpectancy
extern thread_local size_t T01_LifeExpectancy_increments;

/// Report resource use of  T01_LifeExpectancy.
auto om_T01_LifeExpectancy_resource_use(void);

/// Reset resource use for  T01_LifeExpectancy.
void om_T01_LifeExpectancy_resource_use_reset(void);

class cls_T02_TotalPopulationByYear final : public EntityTable<1, 101, 2, 2, false, false>
{
public:
    cls_T02_TotalPopulationByYear(const char* name, std::initializer_list<int> shape) : EntityTable<1, 101, 2, 2, false, false>(name, shape)
    {
    }
    void initialize_accumulators();
    void extract_accumulators();
    void scale_accumulators();
    void compute_expressions();
};
typedef cls_T02_TotalPopulationByYear T02_TotalPopulationByYear;
extern thread_local T02_TotalPopulationByYear * theT02_TotalPopulationByYear;

/// Count of increments pushed to table T02_TotalPopulationByYear
extern thread_local size_t T02_TotalPopulationByYear_increments;

/// Report resource use of  T02_TotalPopulationByYear.
auto om_T02_TotalPopulationByYear_resource_use(void);

/// Reset resource use for  T02_TotalPopulationByYear.
void om_T02_TotalPopulationByYear_resource_use_reset(void);

class cls_T03_FertilityByAge final : public EntityTable<1, 27, 2, 3, false, false>
{
public:
    cls_T03_FertilityByAge(const char* name, std::initializer_list<int> shape) : EntityTable<1, 27, 2, 3, false, false>(name, shape)
    {
    }
    void initialize_accumulators();
    void extract_accumulators();
    void scale_accumulators();
    void compute_expressions();
};
typedef cls_T03_FertilityByAge T03_FertilityByAge;
extern thread_local T03_FertilityByAge * theT03_FertilityByAge;

/// Count of increments pushed to table T03_FertilityByAge
extern thread_local size_t T03_FertilityByAge_increments;

/// Report resource use of  T03_FertilityByAge.
auto om_T03_FertilityByAge_resource_use(void);

/// Reset resource use for  T03_FertilityByAge.
void om_T03_FertilityByAge_resource_use_reset(void);

class cls_T04_FertilityRatesByAgeGroup final : public EntityTable<2, 72, 1, 2, false, false>
{
public:
    cls_T04_FertilityRatesByAgeGroup(const char* name, std::initializer_list<int> shape) : EntityTable<2, 72, 1, 2, false, false>(name, shape)
    {
    }
    void initialize_accumulators();
    void extract_accumulators();
    void scale_accumulators();
    void compute_expressions();
};
typedef cls_T04_FertilityRatesByAgeGroup T04_FertilityRatesByAgeGroup;
extern thread_local T04_FertilityRatesByAgeGroup * theT04_FertilityRatesByAgeGroup;

/// Count of increments pushed to table T04_FertilityRatesByAgeGroup
extern thread_local size_t T04_FertilityRatesByAgeGroup_increments;

/// Report resource use of  T04_FertilityRatesByAgeGroup.
auto om_T04_FertilityRatesByAgeGroup_resource_use(void);

/// Reset resource use for  T04_FertilityRatesByAgeGroup.
void om_T04_FertilityRatesByAgeGroup_resource_use_reset(void);

class cls_T05_CohortFertility final : public EntityTable<0, 1, 3, 3, false, false>
{
public:
    cls_T05_CohortFertility(const char* name, std::initializer_list<int> shape) : EntityTable<0, 1, 3, 3, false, false>(name, shape)
    {
    }
    void initialize_accumulators();
    void extract_accumulators();
    void scale_accumulators();
    void compute_expressions();
};
typedef cls_T05_CohortFertility T05_CohortFertility;
extern thread_local T05_CohortFertility * theT05_CohortFertility;

/// Count of increments pushed to table T05_CohortFertility
extern thread_local size_t T05_CohortFertility_increments;

/// Report resource use of  T05_CohortFertility.
auto om_T05_CohortFertility_resource_use(void);

/// Reset resource use for  T05_CohortFertility.
void om_T05_CohortFertility_resource_use_reset(void);

class cls_T06_BirthsByUnion final : public EntityTable<1, 7, 1, 1, false, false>
{
public:
    cls_T06_BirthsByUnion(const char* name, std::initializer_list<int> shape) : EntityTable<1, 7, 1, 1, false, false>(name, shape)
    {
    }
    void initialize_accumulators();
    void extract_accumulators();
    void scale_accumulators();
    void compute_expressions();
};
typedef cls_T06_BirthsByUnion T06_BirthsByUnion;
extern thread_local T06_BirthsByUnion * theT06_BirthsByUnion;

/// Count of increments pushed to table T06_BirthsByUnion
extern thread_local size_t T06_BirthsByUnion_increments;

/// Report resource use of  T06_BirthsByUnion.
auto om_T06_BirthsByUnion_resource_use(void);

/// Reset resource use for  T06_BirthsByUnion.
void om_T06_BirthsByUnion_resource_use_reset(void);

class cls_T07_FirstUnionFormation final : public EntityTable<1, 12, 1, 2, false, false>
{
public:
    cls_T07_FirstUnionFormation(const char* name, std::initializer_list<int> shape) : EntityTable<1, 12, 1, 2, false, false>(name, shape)
    {
    }
    void initialize_accumulators();
    void extract_accumulators();
    void scale_accumulators();
    void compute_expressions();
};
typedef cls_T07_FirstUnionFormation T07_FirstUnionFormation;
extern thread_local T07_FirstUnionFormation * theT07_FirstUnionFormation;

/// Count of increments pushed to table T07_FirstUnionFormation
extern thread_local size_t T07_FirstUnionFormation_increments;

/// Report resource use of  T07_FirstUnionFormation.
auto om_T07_FirstUnionFormation_resource_use(void);

/// Reset resource use for  T07_FirstUnionFormation.
void om_T07_FirstUnionFormation_resource_use_reset(void);

// derived tables

/// Internal tables of the model
extern const std::unordered_set<std::string> om_internal_table_names;

/// Compute suppressed tables: not computed due to table suppression
extern std::unordered_set<std::string> om_compute_suppressed;

// forward declarations of model entity classes (for links)
class Person;

// model entity classes
class Person : public Entity<Person>
{
public:

    /// The name of this entity
    static constexpr const char * entity_name = "Person";

    /// The kind of this entity
    static constexpr const int entity_kind = 0;

    /// Get the name of this entity
    const char * om_get_entity_name()
    {
        return entity_name;
    }

    //
    // function members in Person entity
    //

    /// operator overload for entity comparison based on entity_id
    bool operator< ( Person & rhs )
    {
        return entity_id < rhs.entity_id;
    }

    /// Implement the event DeathEvent when it occurs in the Person entity (model code).
    void DeathEvent();

    /// Function finishing the life of an actor
    void Finish();

    /// Implement the event FirstPregEvent when it occurs in the Person entity (model code).
    void FirstPregEvent();

    /// Function starting the life of an actor
    void Start();

    /// Implement the event Union1DissolutionEvent when it occurs in the Person entity (model code).
    void Union1DissolutionEvent();

    /// Implement the event Union1FormationEvent when it occurs in the Person entity (model code).
    void Union1FormationEvent();

    /// Implement the event Union2DissolutionEvent when it occurs in the Person entity (model code).
    void Union2DissolutionEvent();

    /// Implement the event Union2FormationEvent when it occurs in the Person entity (model code).
    void Union2FormationEvent();

    /// Implement the event UnionPeriod2Event when it occurs in the Person entity (model code).
    void UnionPeriod2Event();

    /// Age the entity to the given time.
    void age_entity(Time t);

    /// Evaluate and assign expression for age_status.
    void age_status_update_identity();

    /// Check that argument is not in past of entity, else throw run-time exception.
    Time check_time(Time t);

    /// Evaluate and assign expression for dissolution_duration.
    void dissolution_duration_update_identity();

    /// Evaluate and assign expression for dissolution_hazard.
    void dissolution_hazard_update_identity();

    /// Evaluate and assign expression for formation_hazard.
    void formation_hazard_update_identity();

    /// Get censor_time of this entity.
    Time get_censor_time();

    /// Get entity key.
    uint64_t get_entity_key();

    /// Get microdata key.
    uint64_t get_microdata_key();

    /// Evaluate and assign expression for in_union.
    void in_union_update_identity();

    /// Evaluate and assign expression for integer_age.
    void integer_age_update_identity();

    /// Compute the current cell index of table T01_LifeExpectancy using attributes in the Person entity.
    size_t om_T01_LifeExpectancy_current_cell();

    /// Initialize the increment for the active table cell in T01_LifeExpectancy.
    void om_T01_LifeExpectancy_init_increment(int pending, big_counter pending_event_counter);

    /// Finalize the increment and push it to the accumulators in T01_LifeExpectancy.
    void om_T01_LifeExpectancy_push_increment(size_t cell_in, int pending, big_counter pending_event_counter);

    /// Compute the current cell index of table T02_TotalPopulationByYear using attributes in the Person entity.
    size_t om_T02_TotalPopulationByYear_current_cell();

    /// Initialize the increment for the active table cell in T02_TotalPopulationByYear.
    void om_T02_TotalPopulationByYear_init_increment(int pending, big_counter pending_event_counter);

    /// Finalize the increment and push it to the accumulators in T02_TotalPopulationByYear.
    void om_T02_TotalPopulationByYear_push_increment(size_t cell_in, int pending, big_counter pending_event_counter);

    /// Compute the current cell index of table T03_FertilityByAge using attributes in the Person entity.
    size_t om_T03_FertilityByAge_current_cell();

    /// Initialize the increment for the active table cell in T03_FertilityByAge.
    void om_T03_FertilityByAge_init_increment(int pending, big_counter pending_event_counter);

    /// Finalize the increment and push it to the accumulators in T03_FertilityByAge.
    void om_T03_FertilityByAge_push_increment(size_t cell_in, int pending, big_counter pending_event_counter);

    /// Compute the current cell index of table T04_FertilityRatesByAgeGroup using attributes in the Person entity.
    size_t om_T04_FertilityRatesByAgeGroup_current_cell();

    /// Initialize the increment for the active table cell in T04_FertilityRatesByAgeGroup.
    void om_T04_FertilityRatesByAgeGroup_init_increment(int pending, big_counter pending_event_counter);

    /// Finalize the increment and push it to the accumulators in T04_FertilityRatesByAgeGroup.
    void om_T04_FertilityRatesByAgeGroup_push_increment(size_t cell_in, int pending, big_counter pending_event_counter);

    /// Compute the current cell index of table T05_CohortFertility using attributes in the Person entity.
    size_t om_T05_CohortFertility_current_cell();

    /// Initialize the increment for the active table cell in T05_CohortFertility.
    void om_T05_CohortFertility_init_increment(int pending, big_counter pending_event_counter);

    /// Finalize the increment and push it to the accumulators in T05_CohortFertility.
    void om_T05_CohortFertility_push_increment(size_t cell_in, int pending, big_counter pending_event_counter);

    /// Compute the current cell index of table T06_BirthsByUnion using attributes in the Person entity.
    size_t om_T06_BirthsByUnion_current_cell();

    /// Initialize the increment for the active table cell in T06_BirthsByUnion.
    void om_T06_BirthsByUnion_init_increment(int pending, big_counter pending_event_counter);

    /// Finalize the increment and push it to the accumulators in T06_BirthsByUnion.
    void om_T06_BirthsByUnion_push_increment(size_t cell_in, int pending, big_counter pending_event_counter);

    /// Compute the current cell index of table T07_FirstUnionFormation using attributes in the Person entity.
    size_t om_T07_FirstUnionFormation_current_cell();

    /// Initialize the increment for the active table cell in T07_FirstUnionFormation.
    void om_T07_FirstUnionFormation_init_increment(int pending, big_counter pending_event_counter);

    /// Finalize the increment and push it to the accumulators in T07_FirstUnionFormation.
    void om_T07_FirstUnionFormation_push_increment(size_t cell_in, int pending, big_counter pending_event_counter);

    /// Evaluate and assign expression for om_aia_0.
    void om_aia_0_update_identity();

    /// Evaluate and assign expression for om_aia_1.
    void om_aia_1_update_identity();

    /// Evaluate and assign expression for om_aia_2.
    void om_aia_2_update_identity();

    /// Evaluate and assign expression for om_aia_3.
    void om_aia_3_update_identity();

    /// Evaluate and assign expression for om_aia_4.
    void om_aia_4_update_identity();

    /// One-time calculation of the offsets of attributes and increments in the containing entity.
    void om_assign_member_offsets();

    /// Check that starting value of time is valid and raise run-time error if not.
    void om_check_starting_time();

    /// Remove the entity in each entity set when it leaves the simulation.
    void om_finalize_entity_sets();

    /// Remove each event in the entity from the event queue when it leaves the simulation.
    void om_finalize_events();

    /// Set all links in entity to nullptr when the entity leaves the simulation.
    void om_finalize_links();

    /// Empty all multilinks in entity when the entity leaves the simulation.
    void om_finalize_multilinks();

    /// Finish the entity's pending increments in each table when it leaves the simulation.
    void om_finalize_tables();

    /// Return current age of this entity.
    Time om_get_age();

    /// Return unique entity_id of this entity.
    int om_get_entity_id();

    /// Return current time of this entity.
    Time om_get_time();

    /// Initialization of data members before the entity enters simulation.
    void om_initialize_data_members();

    /// Initialization of data members of the 'zero' entity to default values for the type (0).
    void om_initialize_data_members0();

    /// Initialize derived attributes before the entity enters the simulation.
    void om_initialize_derived_attributes();

    /// Insert the entity in each entity set when it enters the simulation.
    void om_initialize_entity_sets();

    /// Force event time calculation for each event in the entity when it enters simulation.
    void om_initialize_events();

    /// Initialize each identity attribute before developer code in Start executes.
    void om_initialize_identity_attributes();

    /// Initialize the entity's increments in each table when it enters the simulation.
    void om_initialize_tables();

    /// Initialize time and age for this entity.
    void om_initialize_time_and_age();

    /// Maintain lifecycle attributes on enter_simulation.
    void om_lifecycle_enter();

    /// Maintain lifecycle attributes at events.
    void om_lifecycle_event(int event_id);

    /// Maintain lifecycle attributes on exit_simulation.
    void om_lifecycle_exit();

    /// Implement notification before changing age in entity Person.
    void om_notify_age();

    /// Implement notification before changing age_status in entity Person.
    void om_notify_age_status();

    /// Implement notification before changing case_id in entity Person.
    void om_notify_case_id();

    /// Implement notification before changing case_seed in entity Person.
    void om_notify_case_seed();

    /// Implement notification before changing dissolution_duration in entity Person.
    void om_notify_dissolution_duration();

    /// Implement notification before changing dissolution_hazard in entity Person.
    void om_notify_dissolution_hazard();

    /// Implement notification before changing entity_id in entity Person.
    void om_notify_entity_id();

    /// Implement notification before changing formation_hazard in entity Person.
    void om_notify_formation_hazard();

    /// Implement notification before changing in_union in entity Person.
    void om_notify_in_union();

    /// Implement notification before changing integer_age in entity Person.
    void om_notify_integer_age();

    /// Implement notification before changing life_status in entity Person.
    void om_notify_life_status();

    /// Implement notification before changing lifecycle_counter in entity Person.
    void om_notify_lifecycle_counter();

    /// Implement notification before changing lifecycle_event in entity Person.
    void om_notify_lifecycle_event();

    /// Implement notification before changing om_active_spell_duration_FOR_in_union_X_true in entity Person.
    void om_notify_om_active_spell_duration_FOR_in_union_X_true();

    /// Implement notification before changing om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION in entity Person.
    void om_notify_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION();

    /// Implement notification before changing om_aia_0 in entity Person.
    void om_notify_om_aia_0();

    /// Implement notification before changing om_aia_1 in entity Person.
    void om_notify_om_aia_1();

    /// Implement notification before changing om_aia_2 in entity Person.
    void om_notify_om_aia_2();

    /// Implement notification before changing om_aia_3 in entity Person.
    void om_notify_om_aia_3();

    /// Implement notification before changing om_aia_4 in entity Person.
    void om_notify_om_aia_4();

    /// Implement notification before changing om_duration in entity Person.
    void om_notify_om_duration();

    /// Implement notification before changing om_duration_FOR_parity_status_X_PS_CHILDLESS in entity Person.
    void om_notify_om_duration_FOR_parity_status_X_PS_CHILDLESS();

    /// Implement notification before changing om_duration_FOR_union_status_X_US_NEVER_IN_UNION in entity Person.
    void om_notify_om_duration_FOR_union_status_X_US_NEVER_IN_UNION();

    /// Implement notification before changing om_entrances_FOR_union_status_X_US_FIRST_UNION_PERIOD1 in entity Person.
    void om_notify_om_entrances_FOR_union_status_X_US_FIRST_UNION_PERIOD1();

    /// Implement notification before changing om_self_scheduling_int_FOR_age in entity Person.
    void om_notify_om_self_scheduling_int_FOR_age();

    /// Implement notification before changing om_self_scheduling_split_FOR_age_X_AGEINT_STATE in entity Person.
    void om_notify_om_self_scheduling_split_FOR_age_X_AGEINT_STATE();

    /// Implement notification before changing om_self_scheduling_split_FOR_age_X_AGE_FERTILEYEARS in entity Person.
    void om_notify_om_self_scheduling_split_FOR_age_X_AGE_FERTILEYEARS();

    /// Implement notification before changing om_self_scheduling_split_FOR_om_active_spell_duration_FOR_in_union_X_true_X_UNION_DURATION in entity Person.
    void om_notify_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_in_union_X_true_X_UNION_DURATION();

    /// Implement notification before changing om_self_scheduling_split_FOR_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION_X_DISSOLUTION_DURATION in entity Person.
    void om_notify_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION_X_DISSOLUTION_DURATION();

    /// Implement notification before changing om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT in entity Person.
    void om_notify_om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT();

    /// Implement notification before changing om_trigger_entrances_FOR_parity_status_X_PS_PREGNANT in entity Person.
    void om_notify_om_trigger_entrances_FOR_parity_status_X_PS_PREGNANT();

    /// Implement notification before changing om_value_at_transitions_FOR_parity_status_X_PS_CHILDLESS_X_age_X_PS_PREGNANT in entity Person.
    void om_notify_om_value_at_transitions_FOR_parity_status_X_PS_CHILDLESS_X_age_X_PS_PREGNANT();

    /// Implement notification before changing parity_status in entity Person.
    void om_notify_parity_status();

    /// Implement notification before changing preg_hazard in entity Person.
    void om_notify_preg_hazard();

    /// Implement notification before changing time in entity Person.
    void om_notify_time();

    /// Implement notification before changing union_duration in entity Person.
    void om_notify_union_duration();

    /// Implement notification before changing union_period2_change in entity Person.
    void om_notify_union_period2_change();

    /// Implement notification before changing union_status in entity Person.
    void om_notify_union_status();

    /// Implement notification before changing unions in entity Person.
    void om_notify_unions();

    /// Reset derived attributes before the entity enters the simulation.
    void om_reset_derived_attributes();

    /// Set the unique entity_id of this entity.
    void om_set_entity_id();

    /// Implement side effects of changing age in entity Person.
    void om_side_effects_age(Time om_old, Time om_new);

    /// Implement side effects of changing age_status in entity Person.
    void om_side_effects_age_status(int om_old, int om_new);

    /// Implement side effects of changing case_id in entity Person.
    void om_side_effects_case_id(llong om_old, llong om_new);

    /// Implement side effects of changing case_seed in entity Person.
    void om_side_effects_case_seed(double om_old, double om_new);

    /// Implement side effects of changing dissolution_duration in entity Person.
    void om_side_effects_dissolution_duration(int om_old, int om_new);

    /// Implement side effects of changing dissolution_hazard in entity Person.
    void om_side_effects_dissolution_hazard(double om_old, double om_new);

    /// Implement side effects of changing entity_id in entity Person.
    void om_side_effects_entity_id(int om_old, int om_new);

    /// Implement side effects of changing formation_hazard in entity Person.
    void om_side_effects_formation_hazard(double om_old, double om_new);

    /// Implement side effects of changing in_union in entity Person.
    void om_side_effects_in_union(bool om_old, bool om_new);

    /// Implement side effects of changing integer_age in entity Person.
    void om_side_effects_integer_age(LIFE om_old, LIFE om_new);

    /// Implement side effects of changing life_status in entity Person.
    void om_side_effects_life_status(LIFE_STATE om_old, LIFE_STATE om_new);

    /// Implement side effects of changing lifecycle_counter in entity Person.
    void om_side_effects_lifecycle_counter(short om_old, short om_new);

    /// Implement side effects of changing lifecycle_event in entity Person.
    void om_side_effects_lifecycle_event(LIFECYCLE_Person om_old, LIFECYCLE_Person om_new);

    /// Implement side effects of changing om_active_spell_duration_FOR_in_union_X_true in entity Person.
    void om_side_effects_om_active_spell_duration_FOR_in_union_X_true(Time om_old, Time om_new);

    /// Implement side effects of changing om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION in entity Person.
    void om_side_effects_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION(Time om_old, Time om_new);

    /// Implement side effects of changing om_aia_0 in entity Person.
    void om_side_effects_om_aia_0(bool om_old, bool om_new);

    /// Implement side effects of changing om_aia_1 in entity Person.
    void om_side_effects_om_aia_1(bool om_old, bool om_new);

    /// Implement side effects of changing om_aia_2 in entity Person.
    void om_side_effects_om_aia_2(bool om_old, bool om_new);

    /// Implement side effects of changing om_aia_3 in entity Person.
    void om_side_effects_om_aia_3(bool om_old, bool om_new);

    /// Implement side effects of changing om_aia_4 in entity Person.
    void om_side_effects_om_aia_4(bool om_old, bool om_new);

    /// Implement side effects of changing om_duration in entity Person.
    void om_side_effects_om_duration(Time om_old, Time om_new);

    /// Implement side effects of changing om_duration_FOR_parity_status_X_PS_CHILDLESS in entity Person.
    void om_side_effects_om_duration_FOR_parity_status_X_PS_CHILDLESS(Time om_old, Time om_new);

    /// Implement side effects of changing om_duration_FOR_union_status_X_US_NEVER_IN_UNION in entity Person.
    void om_side_effects_om_duration_FOR_union_status_X_US_NEVER_IN_UNION(Time om_old, Time om_new);

    /// Implement side effects of changing om_entrances_FOR_union_status_X_US_FIRST_UNION_PERIOD1 in entity Person.
    void om_side_effects_om_entrances_FOR_union_status_X_US_FIRST_UNION_PERIOD1(counter om_old, counter om_new);

    /// Implement side effects of changing om_self_scheduling_int_FOR_age in entity Person.
    void om_side_effects_om_self_scheduling_int_FOR_age(integer om_old, integer om_new);

    /// Implement side effects of changing om_self_scheduling_split_FOR_age_X_AGEINT_STATE in entity Person.
    void om_side_effects_om_self_scheduling_split_FOR_age_X_AGEINT_STATE(AGEINT_STATE om_old, AGEINT_STATE om_new);

    /// Implement side effects of changing om_self_scheduling_split_FOR_age_X_AGE_FERTILEYEARS in entity Person.
    void om_side_effects_om_self_scheduling_split_FOR_age_X_AGE_FERTILEYEARS(AGE_FERTILEYEARS om_old, AGE_FERTILEYEARS om_new);

    /// Implement side effects of changing om_self_scheduling_split_FOR_om_active_spell_duration_FOR_in_union_X_true_X_UNION_DURATION in entity Person.
    void om_side_effects_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_in_union_X_true_X_UNION_DURATION(UNION_DURATION om_old, UNION_DURATION om_new);

    /// Implement side effects of changing om_self_scheduling_split_FOR_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION_X_DISSOLUTION_DURATION in entity Person.
    void om_side_effects_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION_X_DISSOLUTION_DURATION(DISSOLUTION_DURATION om_old, DISSOLUTION_DURATION om_new);

    /// Implement side effects of changing om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT in entity Person.
    void om_side_effects_om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT(counter om_old, counter om_new);

    /// Implement side effects of changing om_trigger_entrances_FOR_parity_status_X_PS_PREGNANT in entity Person.
    void om_side_effects_om_trigger_entrances_FOR_parity_status_X_PS_PREGNANT(bool om_old, bool om_new);

    /// Implement side effects of changing om_value_at_transitions_FOR_parity_status_X_PS_CHILDLESS_X_age_X_PS_PREGNANT in entity Person.
    void om_side_effects_om_value_at_transitions_FOR_parity_status_X_PS_CHILDLESS_X_age_X_PS_PREGNANT(real om_old, real om_new);

    /// Implement side effects of changing parity_status in entity Person.
    void om_side_effects_parity_status(PARITY_STATE om_old, PARITY_STATE om_new);

    /// Implement side effects of changing preg_hazard in entity Person.
    void om_side_effects_preg_hazard(double om_old, double om_new);

    /// Implement side effects of changing time in entity Person.
    void om_side_effects_time(Time om_old, Time om_new);

    /// Implement side effects of changing union_duration in entity Person.
    void om_side_effects_union_duration(int om_old, int om_new);

    /// Implement side effects of changing union_period2_change in entity Person.
    void om_side_effects_union_period2_change(Time om_old, Time om_new);

    /// Implement side effects of changing union_status in entity Person.
    void om_side_effects_union_status(UNION_STATE om_old, UNION_STATE om_new);

    /// Implement side effects of changing unions in entity Person.
    void om_side_effects_unions(int om_old, int om_new);

    /// Implement function for the self-scheduling event.
    void om_ss_event();

    /// Time function for the self-scheduling event.
    Time om_ss_time();

    /// Perform trace operations at start of entity lifecycle.
    void om_start_trace();

    /// Evaluate and assign expression for preg_hazard.
    void preg_hazard_update_identity();

    /// Set censor_time of this entity.
    void set_censor_time(Time t);

    /// Return the time to the event DeathEvent in the Person entity (model code).
    Time timeDeathEvent();

    /// Return the time to the event FirstPregEvent in the Person entity (model code).
    Time timeFirstPregEvent();

    /// Return the time to the event Union1DissolutionEvent in the Person entity (model code).
    Time timeUnion1DissolutionEvent();

    /// Return the time to the event Union1FormationEvent in the Person entity (model code).
    Time timeUnion1FormationEvent();

    /// Return the time to the event Union2DissolutionEvent in the Person entity (model code).
    Time timeUnion2DissolutionEvent();

    /// Return the time to the event Union2FormationEvent in the Person entity (model code).
    Time timeUnion2FormationEvent();

    /// Return the time to the event UnionPeriod2Event in the Person entity (model code).
    Time timeUnionPeriod2Event();

    /// Evaluate and assign expression for union_duration.
    void union_duration_update_identity();

    /// Handle microdata output.
    void write_microdata();


    //
    // Data members in Person entity
    //


    //////////////////////////////////////////////
    // Layout Group = 1
    //////////////////////////////////////////////


    /// entity_id
    static const std::string om_name_entity_id;
    typedef AssignableAttribute<int, void, Person, &om_name_entity_id, false, &Person::om_side_effects_entity_id, false, &Person::om_notify_entity_id, false> entity_id_om_type;
    /// attribute(built-in) int: Entity identifier
    entity_id_om_type entity_id;

    //////////////////////////////////////////////
    // Layout Group = 2
    //////////////////////////////////////////////


    /// time
    static const std::string om_name_time;
    typedef AssignableAttribute<Time, double, Person, &om_name_time, true, &Person::om_side_effects_time, true, &Person::om_notify_time, false> time_om_type;
    /// attribute(built-in) Time: Time
    time_om_type time;

    //////////////////////////////////////////////
    // Layout Group = 3
    //////////////////////////////////////////////


    /// age
    static const std::string om_name_age;
    typedef AssignableAttribute<Time, double, Person, &om_name_age, true, &Person::om_side_effects_age, true, &Person::om_notify_age, false> age_om_type;
    /// attribute(built-in) Time: Age
    age_om_type age;

    //////////////////////////////////////////////
    // Layout Group = 4
    //////////////////////////////////////////////


    /// age_status
    static const std::string om_name_age_status;
    typedef Attribute<int, void, Person, &om_name_age_status, false, &Person::om_side_effects_age_status, true, &Person::om_notify_age_status, false> age_status_om_type;
    /// attribute(identity) int: Current age interval
    age_status_om_type age_status;

    /// case_id
    static const std::string om_name_case_id;
    typedef AssignableAttribute<llong, void, Person, &om_name_case_id, false, &Person::om_side_effects_case_id, false, &Person::om_notify_case_id, false> case_id_om_type;
    /// attribute(built-in) llong: Case identifier
    case_id_om_type case_id;

    /// case_seed
    static const std::string om_name_case_seed;
    typedef AssignableAttribute<double, void, Person, &om_name_case_seed, false, &Person::om_side_effects_case_seed, false, &Person::om_notify_case_seed, false> case_seed_om_type;
    /// attribute(built-in) double: Case seed for random number generators
    case_seed_om_type case_seed;

    /// dissolution_duration
    static const std::string om_name_dissolution_duration;
    typedef Attribute<int, void, Person, &om_name_dissolution_duration, false, &Person::om_side_effects_dissolution_duration, true, &Person::om_notify_dissolution_duration, false> dissolution_duration_om_type;
    /// attribute(identity) int: Time interval since union dissolution
    dissolution_duration_om_type dissolution_duration;

    /// dissolution_hazard
    static const std::string om_name_dissolution_hazard;
    typedef Attribute<double, void, Person, &om_name_dissolution_hazard, false, &Person::om_side_effects_dissolution_hazard, false, &Person::om_notify_dissolution_hazard, false> dissolution_hazard_om_type;
    /// attribute(identity) double: Union dissolution hazard
    dissolution_hazard_om_type dissolution_hazard;

    /// formation_hazard
    static const std::string om_name_formation_hazard;
    typedef Attribute<double, void, Person, &om_name_formation_hazard, false, &Person::om_side_effects_formation_hazard, false, &Person::om_notify_formation_hazard, false> formation_hazard_om_type;
    /// attribute(identity) double: Union formation hazard
    formation_hazard_om_type formation_hazard;

    /// in_union
    static const std::string om_name_in_union;
    typedef Attribute<bool, void, Person, &om_name_in_union, false, &Person::om_side_effects_in_union, true, &Person::om_notify_in_union, false> in_union_om_type;
    /// attribute(identity) bool: Currently in an union
    in_union_om_type in_union;

    /// integer_age
    static const std::string om_name_integer_age;
    typedef Attribute<LIFE, int, Person, &om_name_integer_age, false, &Person::om_side_effects_integer_age, true, &Person::om_notify_integer_age, true> integer_age_om_type;
    /// attribute(identity) LIFE: Current integer age
    integer_age_om_type integer_age;

    /// life_status
    static const std::string om_name_life_status;
    typedef AssignableAttribute<LIFE_STATE, int, Person, &om_name_life_status, false, &Person::om_side_effects_life_status, false, &Person::om_notify_life_status, false> life_status_om_type;
    /// attribute(simple) LIFE_STATE: Life Status
    life_status_om_type life_status;

    /// lifecycle_counter
    static const std::string om_name_lifecycle_counter;
    typedef AssignableAttribute<short, void, Person, &om_name_lifecycle_counter, false, &Person::om_side_effects_lifecycle_counter, false, &Person::om_notify_lifecycle_counter, false> lifecycle_counter_om_type;
    /// attribute(built-in) short: Lifecycle counter
    lifecycle_counter_om_type lifecycle_counter;

    /// lifecycle_event
    static const std::string om_name_lifecycle_event;
    typedef AssignableAttribute<LIFECYCLE_Person, int, Person, &om_name_lifecycle_event, false, &Person::om_side_effects_lifecycle_event, false, &Person::om_notify_lifecycle_event, false> lifecycle_event_om_type;
    /// attribute(built-in) LIFECYCLE_Person: Lifecycle event
    lifecycle_event_om_type lifecycle_event;

    /// parity_status
    static const std::string om_name_parity_status;
    typedef AssignableAttribute<PARITY_STATE, int, Person, &om_name_parity_status, false, &Person::om_side_effects_parity_status, true, &Person::om_notify_parity_status, false> parity_status_om_type;
    /// attribute(simple) PARITY_STATE: Parity status derived from the state parity
    parity_status_om_type parity_status;

    /// preg_hazard
    static const std::string om_name_preg_hazard;
    typedef Attribute<double, void, Person, &om_name_preg_hazard, false, &Person::om_side_effects_preg_hazard, false, &Person::om_notify_preg_hazard, false> preg_hazard_om_type;
    /// attribute(identity) double: Pregnancy hazard
    preg_hazard_om_type preg_hazard;

    /// union_duration
    static const std::string om_name_union_duration;
    typedef Attribute<int, void, Person, &om_name_union_duration, false, &Person::om_side_effects_union_duration, true, &Person::om_notify_union_duration, false> union_duration_om_type;
    /// attribute(identity) int: Time interval since union formation
    union_duration_om_type union_duration;

    /// union_period2_change
    static const std::string om_name_union_period2_change;
    typedef AssignableAttribute<Time, double, Person, &om_name_union_period2_change, false, &Person::om_side_effects_union_period2_change, true, &Person::om_notify_union_period2_change, false> union_period2_change_om_type;
    /// attribute(simple) Time: Time of union period change
    union_period2_change_om_type union_period2_change;

    /// union_status
    static const std::string om_name_union_status;
    typedef AssignableAttribute<UNION_STATE, int, Person, &om_name_union_status, false, &Person::om_side_effects_union_status, true, &Person::om_notify_union_status, true> union_status_om_type;
    /// attribute(simple) UNION_STATE: Union status
    union_status_om_type union_status;

    /// unions
    static const std::string om_name_unions;
    typedef AssignableAttribute<int, void, Person, &om_name_unions, false, &Person::om_side_effects_unions, false, &Person::om_notify_unions, false> unions_om_type;
    /// attribute(simple) int: Union counter
    unions_om_type unions;

    //////////////////////////////////////////////
    // Layout Group = 9
    //////////////////////////////////////////////


    /// DeathEvent
    Event<Person, 0, 0, 0, &Person::DeathEvent, &Person::timeDeathEvent>
    om_DeathEvent_om_event;

    /// FirstPregEvent
    Event<Person, 1, 0, 1, &Person::FirstPregEvent, &Person::timeFirstPregEvent>
    om_FirstPregEvent_om_event;

    /// T01_LifeExpectancy (in) om_duration
    Time om_T01_LifeExpectancy_in_om_duration;

    /// T01_LifeExpectancy increment

    static const std::string om_name_om_T01_LifeExpectancy_incr;
    /// T01_LifeExpectancy increment
    Increment<Person, uint8_t, &om_name_om_T01_LifeExpectancy_incr, &Person::om_T01_LifeExpectancy_init_increment, &Person::om_T01_LifeExpectancy_push_increment>
    om_T01_LifeExpectancy_incr;

    /// T02_TotalPopulationByYear (in) om_duration
    Time om_T02_TotalPopulationByYear_in_om_duration;

    /// T02_TotalPopulationByYear increment

    static const std::string om_name_om_T02_TotalPopulationByYear_incr;
    /// T02_TotalPopulationByYear increment
    Increment<Person, uint8_t, &om_name_om_T02_TotalPopulationByYear_incr, &Person::om_T02_TotalPopulationByYear_init_increment, &Person::om_T02_TotalPopulationByYear_push_increment>
    om_T02_TotalPopulationByYear_incr;

    /// T03_FertilityByAge (in) om_duration
    Time om_T03_FertilityByAge_in_om_duration;

    /// T03_FertilityByAge (in) om_duration_FOR_parity_status_X_PS_CHILDLESS
    Time om_T03_FertilityByAge_in_om_duration_FOR_parity_status_X_PS_CHILDLESS;

    /// T03_FertilityByAge (in) om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT
    counter om_T03_FertilityByAge_in_om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT;

    /// T03_FertilityByAge increment

    static const std::string om_name_om_T03_FertilityByAge_incr;
    /// T03_FertilityByAge increment
    Increment<Person, uint8_t, &om_name_om_T03_FertilityByAge_incr, &Person::om_T03_FertilityByAge_init_increment, &Person::om_T03_FertilityByAge_push_increment>
    om_T03_FertilityByAge_incr;

    /// T04_FertilityRatesByAgeGroup (in) om_duration_FOR_parity_status_X_PS_CHILDLESS
    Time om_T04_FertilityRatesByAgeGroup_in_om_duration_FOR_parity_status_X_PS_CHILDLESS;

    /// T04_FertilityRatesByAgeGroup (in) om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT
    counter om_T04_FertilityRatesByAgeGroup_in_om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT;

    /// T04_FertilityRatesByAgeGroup increment

    static const std::string om_name_om_T04_FertilityRatesByAgeGroup_incr;
    /// T04_FertilityRatesByAgeGroup increment
    Increment<Person, uint8_t, &om_name_om_T04_FertilityRatesByAgeGroup_incr, &Person::om_T04_FertilityRatesByAgeGroup_init_increment, &Person::om_T04_FertilityRatesByAgeGroup_push_increment>
    om_T04_FertilityRatesByAgeGroup_incr;

    /// T05_CohortFertility (in) om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT
    counter om_T05_CohortFertility_in_om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT;

    /// T05_CohortFertility (in) om_value_at_transitions_FOR_parity_status_X_PS_CHILDLESS_X_age_X_PS_PREGNANT
    real om_T05_CohortFertility_in_om_value_at_transitions_FOR_parity_status_X_PS_CHILDLESS_X_age_X_PS_PREGNANT;

    /// T05_CohortFertility increment

    static const std::string om_name_om_T05_CohortFertility_incr;
    /// T05_CohortFertility increment
    Increment<Person, uint8_t, &om_name_om_T05_CohortFertility_incr, &Person::om_T05_CohortFertility_init_increment, &Person::om_T05_CohortFertility_push_increment>
    om_T05_CohortFertility_incr;

    /// T06_BirthsByUnion increment

    static const std::string om_name_om_T06_BirthsByUnion_incr;
    /// T06_BirthsByUnion increment
    Increment<Person, uint8_t, &om_name_om_T06_BirthsByUnion_incr, &Person::om_T06_BirthsByUnion_init_increment, &Person::om_T06_BirthsByUnion_push_increment>
    om_T06_BirthsByUnion_incr;

    /// T07_FirstUnionFormation (in) om_duration_FOR_union_status_X_US_NEVER_IN_UNION
    Time om_T07_FirstUnionFormation_in_om_duration_FOR_union_status_X_US_NEVER_IN_UNION;

    /// T07_FirstUnionFormation (in) om_entrances_FOR_union_status_X_US_FIRST_UNION_PERIOD1
    counter om_T07_FirstUnionFormation_in_om_entrances_FOR_union_status_X_US_FIRST_UNION_PERIOD1;

    /// T07_FirstUnionFormation increment

    static const std::string om_name_om_T07_FirstUnionFormation_incr;
    /// T07_FirstUnionFormation increment
    Increment<Person, uint8_t, &om_name_om_T07_FirstUnionFormation_incr, &Person::om_T07_FirstUnionFormation_init_increment, &Person::om_T07_FirstUnionFormation_push_increment>
    om_T07_FirstUnionFormation_incr;

    /// Union1DissolutionEvent
    Event<Person, 2, 0, 2, &Person::Union1DissolutionEvent, &Person::timeUnion1DissolutionEvent>
    om_Union1DissolutionEvent_om_event;

    /// Union1FormationEvent
    Event<Person, 3, 0, 3, &Person::Union1FormationEvent, &Person::timeUnion1FormationEvent>
    om_Union1FormationEvent_om_event;

    /// Union2DissolutionEvent
    Event<Person, 4, 0, 4, &Person::Union2DissolutionEvent, &Person::timeUnion2DissolutionEvent>
    om_Union2DissolutionEvent_om_event;

    /// Union2FormationEvent
    Event<Person, 5, 0, 5, &Person::Union2FormationEvent, &Person::timeUnion2FormationEvent>
    om_Union2FormationEvent_om_event;

    /// UnionPeriod2Event
    Event<Person, 6, 0, 6, &Person::UnionPeriod2Event, &Person::timeUnionPeriod2Event>
    om_UnionPeriod2Event_om_event;

    /// active_spell_duration(in_union,true)
    static const std::string om_name_om_active_spell_duration_FOR_in_union_X_true;
    Attribute<Time, double, Person, &om_name_om_active_spell_duration_FOR_in_union_X_true, true, &Person::om_side_effects_om_active_spell_duration_FOR_in_union_X_true, false, &Person::om_notify_om_active_spell_duration_FOR_in_union_X_true, false>
    om_active_spell_duration_FOR_in_union_X_true;

    /// active_spell_duration(union_status,US_AFTER_FIRST_UNION)
    static const std::string om_name_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION;
    Attribute<Time, double, Person, &om_name_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION, true, &Person::om_side_effects_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION, false, &Person::om_notify_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION, false>
    om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION;

    /// om_aia_0
    static const std::string om_name_om_aia_0;
    typedef Attribute<bool, void, Person, &om_name_om_aia_0, false, &Person::om_side_effects_om_aia_0, true, &Person::om_notify_om_aia_0, true> om_aia_0_om_type;
    /// attribute(identity) bool: (parity_status == PS_CHILDLESS)
    om_aia_0_om_type om_aia_0;

    /// om_aia_1
    static const std::string om_name_om_aia_1;
    typedef Attribute<bool, void, Person, &om_name_om_aia_1, false, &Person::om_side_effects_om_aia_1, true, &Person::om_notify_om_aia_1, true> om_aia_1_om_type;
    /// attribute(identity) bool: trigger_entrances(parity_status,PS_PREGNANT)
    om_aia_1_om_type om_aia_1;

    /// om_aia_2
    static const std::string om_name_om_aia_2;
    typedef Attribute<bool, void, Person, &om_name_om_aia_2, false, &Person::om_side_effects_om_aia_2, false, &Person::om_notify_om_aia_2, false> om_aia_2_om_type;
    /// attribute(identity) bool: (union_status == US_NEVER_IN_UNION)
    om_aia_2_om_type om_aia_2;

    /// om_aia_3
    static const std::string om_name_om_aia_3;
    typedef Attribute<bool, void, Person, &om_name_om_aia_3, false, &Person::om_side_effects_om_aia_3, true, &Person::om_notify_om_aia_3, false> om_aia_3_om_type;
    /// attribute(identity) bool: (in_union == true)
    om_aia_3_om_type om_aia_3;

    /// om_aia_4
    static const std::string om_name_om_aia_4;
    typedef Attribute<bool, void, Person, &om_name_om_aia_4, false, &Person::om_side_effects_om_aia_4, true, &Person::om_notify_om_aia_4, false> om_aia_4_om_type;
    /// attribute(identity) bool: (union_status == US_AFTER_FIRST_UNION)
    om_aia_4_om_type om_aia_4;

    /// duration()
    static const std::string om_name_om_duration;
    Attribute<Time, double, Person, &om_name_om_duration, true, &Person::om_side_effects_om_duration, false, &Person::om_notify_om_duration, true>
    om_duration;

    /// duration(parity_status,PS_CHILDLESS)
    static const std::string om_name_om_duration_FOR_parity_status_X_PS_CHILDLESS;
    Attribute<Time, double, Person, &om_name_om_duration_FOR_parity_status_X_PS_CHILDLESS, true, &Person::om_side_effects_om_duration_FOR_parity_status_X_PS_CHILDLESS, false, &Person::om_notify_om_duration_FOR_parity_status_X_PS_CHILDLESS, true>
    om_duration_FOR_parity_status_X_PS_CHILDLESS;

    /// duration(union_status,US_NEVER_IN_UNION)
    static const std::string om_name_om_duration_FOR_union_status_X_US_NEVER_IN_UNION;
    Attribute<Time, double, Person, &om_name_om_duration_FOR_union_status_X_US_NEVER_IN_UNION, true, &Person::om_side_effects_om_duration_FOR_union_status_X_US_NEVER_IN_UNION, false, &Person::om_notify_om_duration_FOR_union_status_X_US_NEVER_IN_UNION, true>
    om_duration_FOR_union_status_X_US_NEVER_IN_UNION;

    /// entrances(union_status,US_FIRST_UNION_PERIOD1)
    static const std::string om_name_om_entrances_FOR_union_status_X_US_FIRST_UNION_PERIOD1;
    Attribute<counter, void, Person, &om_name_om_entrances_FOR_union_status_X_US_FIRST_UNION_PERIOD1, false, &Person::om_side_effects_om_entrances_FOR_union_status_X_US_FIRST_UNION_PERIOD1, false, &Person::om_notify_om_entrances_FOR_union_status_X_US_FIRST_UNION_PERIOD1, true>
    om_entrances_FOR_union_status_X_US_FIRST_UNION_PERIOD1;

    /// Person microdata record counter
    short om_microdata_counter;

    /// self_scheduling_int(age)
    static const std::string om_name_om_self_scheduling_int_FOR_age;
    Attribute<integer, void, Person, &om_name_om_self_scheduling_int_FOR_age, false, &Person::om_side_effects_om_self_scheduling_int_FOR_age, true, &Person::om_notify_om_self_scheduling_int_FOR_age, false>
    om_self_scheduling_int_FOR_age;

    /// self_scheduling_split(age,AGEINT_STATE)
    static const std::string om_name_om_self_scheduling_split_FOR_age_X_AGEINT_STATE;
    Attribute<AGEINT_STATE, int, Person, &om_name_om_self_scheduling_split_FOR_age_X_AGEINT_STATE, false, &Person::om_side_effects_om_self_scheduling_split_FOR_age_X_AGEINT_STATE, true, &Person::om_notify_om_self_scheduling_split_FOR_age_X_AGEINT_STATE, true>
    om_self_scheduling_split_FOR_age_X_AGEINT_STATE;

    /// self_scheduling_split(age,AGE_FERTILEYEARS)
    static const std::string om_name_om_self_scheduling_split_FOR_age_X_AGE_FERTILEYEARS;
    Attribute<AGE_FERTILEYEARS, int, Person, &om_name_om_self_scheduling_split_FOR_age_X_AGE_FERTILEYEARS, false, &Person::om_side_effects_om_self_scheduling_split_FOR_age_X_AGE_FERTILEYEARS, true, &Person::om_notify_om_self_scheduling_split_FOR_age_X_AGE_FERTILEYEARS, true>
    om_self_scheduling_split_FOR_age_X_AGE_FERTILEYEARS;

    /// self_scheduling_split(active_spell_duration(in_union,true),UNION_DURATION)
    static const std::string om_name_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_in_union_X_true_X_UNION_DURATION;
    Attribute<UNION_DURATION, int, Person, &om_name_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_in_union_X_true_X_UNION_DURATION, false, &Person::om_side_effects_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_in_union_X_true_X_UNION_DURATION, true, &Person::om_notify_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_in_union_X_true_X_UNION_DURATION, false>
    om_self_scheduling_split_FOR_om_active_spell_duration_FOR_in_union_X_true_X_UNION_DURATION;

    /// self_scheduling_split(active_spell_duration(union_status,US_AFTER_FIRST_UNION),DISSOLUTION_DURATION)
    static const std::string om_name_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION_X_DISSOLUTION_DURATION;
    Attribute<DISSOLUTION_DURATION, int, Person, &om_name_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION_X_DISSOLUTION_DURATION, false, &Person::om_side_effects_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION_X_DISSOLUTION_DURATION, true, &Person::om_notify_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION_X_DISSOLUTION_DURATION, false>
    om_self_scheduling_split_FOR_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION_X_DISSOLUTION_DURATION;

    /// om_self_scheduling_int_FOR_age (next time)
    Time om_ss_time_om_self_scheduling_int_FOR_age;

    /// om_self_scheduling_split_FOR_age_X_AGEINT_STATE (next time)
    Time om_ss_time_om_self_scheduling_split_FOR_age_X_AGEINT_STATE;

    /// om_self_scheduling_split_FOR_age_X_AGE_FERTILEYEARS (next time)
    Time om_ss_time_om_self_scheduling_split_FOR_age_X_AGE_FERTILEYEARS;

    /// om_self_scheduling_split_FOR_om_active_spell_duration_FOR_in_union_X_true_X_UNION_DURATION (next time)
    Time om_ss_time_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_in_union_X_true_X_UNION_DURATION;

    /// om_self_scheduling_split_FOR_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION_X_DISSOLUTION_DURATION (next time)
    Time om_ss_time_om_self_scheduling_split_FOR_om_active_spell_duration_FOR_union_status_X_US_AFTER_FIRST_UNION_X_DISSOLUTION_DURATION;

    /// om_trigger_entrances_FOR_parity_status_X_PS_PREGNANT (next time)
    Time om_ss_time_om_trigger_entrances_FOR_parity_status_X_PS_PREGNANT;

    /// transitions(parity_status,PS_CHILDLESS,PS_PREGNANT)
    static const std::string om_name_om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT;
    Attribute<counter, void, Person, &om_name_om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT, false, &Person::om_side_effects_om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT, false, &Person::om_notify_om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT, true>
    om_transitions_FOR_parity_status_X_PS_CHILDLESS_X_PS_PREGNANT;

    /// trigger_entrances(parity_status,PS_PREGNANT)
    static const std::string om_name_om_trigger_entrances_FOR_parity_status_X_PS_PREGNANT;
    Attribute<bool, void, Person, &om_name_om_trigger_entrances_FOR_parity_status_X_PS_PREGNANT, false, &Person::om_side_effects_om_trigger_entrances_FOR_parity_status_X_PS_PREGNANT, true, &Person::om_notify_om_trigger_entrances_FOR_parity_status_X_PS_PREGNANT, false>
    om_trigger_entrances_FOR_parity_status_X_PS_PREGNANT;

    /// value_at_transitions(parity_status,PS_CHILDLESS,PS_PREGNANT,age)
    static const std::string om_name_om_value_at_transitions_FOR_parity_status_X_PS_CHILDLESS_X_age_X_PS_PREGNANT;
    Attribute<real, void, Person, &om_name_om_value_at_transitions_FOR_parity_status_X_PS_CHILDLESS_X_age_X_PS_PREGNANT, false, &Person::om_side_effects_om_value_at_transitions_FOR_parity_status_X_PS_CHILDLESS_X_age_X_PS_PREGNANT, false, &Person::om_notify_om_value_at_transitions_FOR_parity_status_X_PS_CHILDLESS_X_age_X_PS_PREGNANT, true>
    om_value_at_transitions_FOR_parity_status_X_PS_CHILDLESS_X_age_X_PS_PREGNANT;

    /// om_ss_event
    Event<Person, 7, 255, 7, &Person::om_ss_event, &Person::om_ss_time>
    zzz_om_om_ss_event_om_event;

    /// The static member used to retrieve (zero) values when dereferencing nullptr link attributes.
    static thread_local Person om_null_entity;

    /// Initialize local RNG streams
    void initialize_local_random_streams(void) { }

}; // class Person

void StartSimulation(int id);
void EndSimulation();





