/**
 * @file   om_fixed_parms.cpp
 * Definitions for fixed parameters for model 'RiskPaths' - Generated by openM++ compiler
 *  
 *  Model version = 3.0.0.0
 *  Model created = 2025-05-15 14:47:08.459
 *  Model digest = 2c0eef92573bbab8afa93e6eac19c1c9
 */

#include "omc/cumrate.h"
#include "om_types1.h"

//
// The following pragmas disable known benign warnings in the generated code in this module (om_fixed_parms.cpp)
//
#if defined(_MSC_VER)
    // compiler-specific pragmas for MSVC
#endif
#if defined(__GNUC__)
    // compiler-specific pragmas for gcc
#endif
#if defined(__clang__)
    // compiler-specific pragmas for clang
    #pragma clang diagnostic ignored "-Wunused-const-variable"
#endif

//
// The following constants are used in floating point parameter initializers
//
const double QNAN_F = std::numeric_limits<float>::quiet_NaN();
const double QNAN_D = std::numeric_limits<double>::quiet_NaN();
const double QNAN_LD = std::numeric_limits<long double>::quiet_NaN();

// model parameters (fixed)
