/**
 * @file   om_types1.h
 * Types for model 'RiskPaths' - Generated by openM++ compiler
 *  
 *  Model version = 3.0.0.0
 *  Model created = 2025-05-15 14:47:08.459
 *  Model digest = 2c0eef92573bbab8afa93e6eac19c1c9
 */

#pragma once
#include "om_types0.h"
#include "omc/Range.h"
#include "omc/Partition.h"
#include "omc/Classification.h"
#include "omc/entity_ptr.h"

// templated types

/**
 * Classification: PARITY_STATE
 */
enum om_enum_PARITY_STATE : schar {
    /// Classification PARITY_STATE(PS_CHILDLESS): Childless
    PS_CHILDLESS = 0,

    /// Classification PARITY_STATE(PS_PREGNANT): Pregnant
    PS_PREGNANT,

};
extern const std::string om_name_PARITY_STATE;
/// Classification {0...1}: Parity status
typedef Classification<om_enum_PARITY_STATE, 2, &om_name_PARITY_STATE> PARITY_STATE;
/// C-type of PARITY_STATE (int)
typedef int PARITY_STATE_t; // For use in model code

/**
 * Classification: LIFE_STATE
 */
enum om_enum_LIFE_STATE : schar {
    /// Classification LIFE_STATE(LS_ALIVE): Alive
    LS_ALIVE = 0,

    /// Classification LIFE_STATE(LS_NOT_ALIVE): Dead
    LS_NOT_ALIVE,

};
extern const std::string om_name_LIFE_STATE;
/// Classification {0...1}: Life status
typedef Classification<om_enum_LIFE_STATE, 2, &om_name_LIFE_STATE> LIFE_STATE;
/// C-type of LIFE_STATE (int)
typedef int LIFE_STATE_t; // For use in model code

/**
 * Range: LIFE
 */
extern const std::string om_name_LIFE;
/// Range {0...100}: Simulated age range
typedef Range<schar, 0, 100, &om_name_LIFE> LIFE;
/// C-type of LIFE (int)
typedef int LIFE_t;

/**
 * Partition: AGEINT_STATE
 */
extern const std::array<real, 12> om_AGEINT_STATE_lower;
extern const std::array<real, 12> om_AGEINT_STATE_upper;
extern const std::map<real, schar> om_AGEINT_STATE_splitter;
extern const std::string om_name_AGEINT_STATE;
/// Partition {0...11}: 2.5 year age intervals
typedef Partition<schar, 12, om_AGEINT_STATE_lower, om_AGEINT_STATE_upper, om_AGEINT_STATE_splitter, &om_name_AGEINT_STATE> AGEINT_STATE;
/// C-type of AGEINT_STATE (int)
typedef int AGEINT_STATE_t; // For use in model code

/**
 * Classification: UNION_STATE
 */
enum om_enum_UNION_STATE : schar {
    /// Classification UNION_STATE(US_NEVER_IN_UNION): Never in union
    US_NEVER_IN_UNION = 0,

    /// Classification UNION_STATE(US_FIRST_UNION_PERIOD1): First union < 3 years
    US_FIRST_UNION_PERIOD1,

    /// Classification UNION_STATE(US_FIRST_UNION_PERIOD2): First Union > 3 years
    US_FIRST_UNION_PERIOD2,

    /// Classification UNION_STATE(US_AFTER_FIRST_UNION): After first union
    US_AFTER_FIRST_UNION,

    /// Classification UNION_STATE(US_SECOND_UNION): Second union
    US_SECOND_UNION,

    /// Classification UNION_STATE(US_AFTER_SECOND_UNION): After second union
    US_AFTER_SECOND_UNION,

};
extern const std::string om_name_UNION_STATE;
/// Classification {0...5}: Union status
typedef Classification<om_enum_UNION_STATE, 6, &om_name_UNION_STATE> UNION_STATE;
/// C-type of UNION_STATE (int)
typedef int UNION_STATE_t; // For use in model code

/**
 * Partition: AGE_FERTILEYEARS
 */
extern const std::array<real, 27> om_AGE_FERTILEYEARS_lower;
extern const std::array<real, 27> om_AGE_FERTILEYEARS_upper;
extern const std::map<real, schar> om_AGE_FERTILEYEARS_splitter;
extern const std::string om_name_AGE_FERTILEYEARS;
/// Partition {0...26}: Fertile age partition
typedef Partition<schar, 27, om_AGE_FERTILEYEARS_lower, om_AGE_FERTILEYEARS_upper, om_AGE_FERTILEYEARS_splitter, &om_name_AGE_FERTILEYEARS> AGE_FERTILEYEARS;
/// C-type of AGE_FERTILEYEARS (int)
typedef int AGE_FERTILEYEARS_t; // For use in model code

/**
 * Partition: UNION_DURATION
 */
extern const std::array<real, 6> om_UNION_DURATION_lower;
extern const std::array<real, 6> om_UNION_DURATION_upper;
extern const std::map<real, schar> om_UNION_DURATION_splitter;
extern const std::string om_name_UNION_DURATION;
/// Partition {0...5}: Duration of current union
typedef Partition<schar, 6, om_UNION_DURATION_lower, om_UNION_DURATION_upper, om_UNION_DURATION_splitter, &om_name_UNION_DURATION> UNION_DURATION;
/// C-type of UNION_DURATION (int)
typedef int UNION_DURATION_t; // For use in model code

/**
 * Partition: DISSOLUTION_DURATION
 */
extern const std::array<real, 5> om_DISSOLUTION_DURATION_lower;
extern const std::array<real, 5> om_DISSOLUTION_DURATION_upper;
extern const std::map<real, schar> om_DISSOLUTION_DURATION_splitter;
extern const std::string om_name_DISSOLUTION_DURATION;
/// Partition {0...4}: Duration since union dissolution
typedef Partition<schar, 5, om_DISSOLUTION_DURATION_lower, om_DISSOLUTION_DURATION_upper, om_DISSOLUTION_DURATION_splitter, &om_name_DISSOLUTION_DURATION> DISSOLUTION_DURATION;
/// C-type of DISSOLUTION_DURATION (int)
typedef int DISSOLUTION_DURATION_t; // For use in model code

/**
 * Classification: UNION_ORDER
 */
enum om_enum_UNION_ORDER : schar {
    /// Classification UNION_ORDER(UO_FIRST): First union
    UO_FIRST = 0,

    /// Classification UNION_ORDER(UO_SECOND): Second union
    UO_SECOND,

};
extern const std::string om_name_UNION_ORDER;
/// Classification {0...1}: Union order
typedef Classification<om_enum_UNION_ORDER, 2, &om_name_UNION_ORDER> UNION_ORDER;
/// C-type of UNION_ORDER (int)
typedef int UNION_ORDER_t; // For use in model code

/**
 * Classification: LIFECYCLE_Person
 */
enum om_enum_LIFECYCLE_Person : schar {
    /// Classification LIFECYCLE_Person(LC_Person_enter_simulation): enter simulation
    LC_Person_enter_simulation = 0,

    /// Classification LIFECYCLE_Person(LC_Person_exit_simulation_external): exit simulation (external)
    LC_Person_exit_simulation_external,

    /// Classification LIFECYCLE_Person(LC_Person_DeathEvent): DeathEvent
    LC_Person_DeathEvent,

    /// Classification LIFECYCLE_Person(LC_Person_FirstPregEvent): FirstPregEvent
    LC_Person_FirstPregEvent,

    /// Classification LIFECYCLE_Person(LC_Person_Union1DissolutionEvent): Union1DissolutionEvent
    LC_Person_Union1DissolutionEvent,

    /// Classification LIFECYCLE_Person(LC_Person_Union1FormationEvent): Union1FormationEvent
    LC_Person_Union1FormationEvent,

    /// Classification LIFECYCLE_Person(LC_Person_Union2DissolutionEvent): Union2DissolutionEvent
    LC_Person_Union2DissolutionEvent,

    /// Classification LIFECYCLE_Person(LC_Person_Union2FormationEvent): Union2FormationEvent
    LC_Person_Union2FormationEvent,

    /// Classification LIFECYCLE_Person(LC_Person_UnionPeriod2Event): UnionPeriod2Event
    LC_Person_UnionPeriod2Event,

};
extern const std::string om_name_LIFECYCLE_Person;
/// Classification {0...8}: Lifecycle
typedef Classification<om_enum_LIFECYCLE_Person, 9, &om_name_LIFECYCLE_Person> LIFECYCLE_Person;
/// C-type of LIFECYCLE_Person (int)
typedef int LIFECYCLE_Person_t; // For use in model code

// early forward declarations of entity classes and pointers

class Person;
typedef entity_ptr<Person> Person_ptr;
