/**
 * @file   om_types0.h
 * Fundamental types and constexpr for model 'RiskPaths' - Generated by openM++ compiler
 *  
 *  Model version = 3.0.0.0
 *  Model created = 2025-05-15 14:47:08.459
 *  Model digest = 2c0eef92573bbab8afa93e6eac19c1c9
 */

#pragma once
#include <cmath>
#include <string>
#include "omc/fixed_precision.h"

/// Model was built with bounds_errors = on.
constexpr bool om_bounds_errors = true;

/// Model was built with censor_event_time = off.
constexpr bool om_censor_event_time_on = false;

/// Model was built with weighted_tabulation = off.
constexpr bool om_weighted_tabulation_on = false;

/// Model was built with resource_use = off.
constexpr bool om_resource_use_on = false;

/// Model was not built with event trace capability.
constexpr bool om_event_trace_capable = false;

/// Model was built with microdata output capability.
constexpr bool om_microdata_output_capable = true;

/// Write microdata on entity enter.
constexpr bool om_microdata_write_on_enter = 1;

/// Write microdata on entity exit.
constexpr bool om_microdata_write_on_exit = 1;

/// Write microdata on any event.
constexpr bool om_microdata_write_on_event = 1;

/// Model was built with verification of attribute modification.
constexpr bool om_verify_attribute_modification = true;

/// Model was built with verification of time-like attribute access.
constexpr bool om_verify_timelike_attribute_access = true;

/// Model was built with verification of numeric table increments.
constexpr bool om_verify_valid_table_increment = true;

namespace fmk {
    /// Size of an array whose index is a random number stream in this model.
    constexpr int size_streams = 8;
}

// fundamental types
typedef signed char schar;
typedef long long llong;
typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned int uint;
typedef unsigned long ulong;
typedef unsigned long long ullong;
typedef long double ldouble;
typedef fixed_precision<double> Time;
typedef double Time_t; // For use in model code
typedef fixed_precision<double> TIME;
typedef double TIME_t; // For use in model code
extern const Time_t time_infinite;
extern const Time_t TIME_INFINITE; // For Modgen source compatibility
extern const Time_t time_undef;
extern const Time_t TIME_UNDEF; // For Modgen source compatibility
typedef double real;
#define REAL_MAX DBL_MAX
typedef int integer;
typedef int counter;
typedef unsigned long long big_counter;

namespace omr {
    /// statistic in an entity table
    enum class stat {
        unit,
        sum,
        minimum,
        maximum,
        mean,
        variance,
        stdev,
        P1,
        P2,
        P5,
        P10,
        P20,
        P25,
        P30,
        P40,
        P50,
        P60,
        P70,
        P75,
        P80,
        P90,
        P95,
        P98,
        P99,
        gini,
    };
} // namespace omr

namespace omr {
    /// increment in an entity table
    enum class incr {
        unused,
        delta,
        delta2,
        nz_delta,
        value_in,
        value_in2,
        nz_value_in,
        value_out,
        value_out2,
        nz_value_out,
    };
} // namespace omr

namespace omr {
    /// entity table in model
    enum class etbl {
        T01_LifeExpectancy,
        T02_TotalPopulationByYear,
        T03_FertilityByAge,
        T04_FertilityRatesByAgeGroup,
        T05_CohortFertility,
        T06_BirthsByUnion,
        T07_FirstUnionFormation,
        om_none
    };
} // namespace omr

namespace omr {
    /// visible entity attribute in model
    enum class attr {
        age,
        age_status,
        case_id,
        case_seed,
        dissolution_duration,
        dissolution_hazard,
        entity_id,
        formation_hazard,
        in_union,
        integer_age,
        life_status,
        lifecycle_counter,
        lifecycle_event,
        parity_status,
        preg_hazard,
        time,
        union_duration,
        union_period2_change,
        union_status,
        unions,
        om_none
    };
} // namespace omr

