#!/usr/bin/env bash
#
# build openM++ models
# environmemnt variables:
#  OM_BUILD_CONFIGS=RELEASE,DEBUG (default: RELEASE)
#  OM_MSG_USE=MPI                 (default: EMPTY)
#  MODEL_DIRS=modelOne,NewCaseBased,NewTimeBased,NewCaseBased_bilingual,IDMM,RiskPaths,OzProjGenX,OzProjX,SM1
#  OMPP_BUILD_TAG                 (default: build from latest git)
#  OMPP_CPP_BUILD_TAG             (default: build from latest git)
#
#  OMPP_CPP_BUILD_TAG has higher priority over OMPP_BUILD_TAG

OM_BLD_MDLS=${MODEL_DIRS:-modelOne,NewCaseBased,NewTimeBased,NewCaseBased_bilingual,IDMM,RiskPaths,OzProjGenX,OzProjX,SM1}

OM_BLD_CFG=${OM_BUILD_CONFIGS:-RELEASE}

for C in ${OM_BLD_CFG//,/ }; do
  if [ "$C" != 'RELEASE' ] && [ "$C" != 'DEBUG' ]; then
    echo Error: incorrect value: $C, must be any combination of: RELEASE,DEBUG
    exit 1
  fi
done

if [ -n "$OM_MSG_USE" ] && [ "$OM_MSG_USE" != 'EMPTY' ] && [ "$OM_MSG_USE" != 'MPI' ]; then
  echo Error: incorrect value: $OM_MSG_USE, must be one of: MPI or EMPTY
  exit 1
fi

[ "$OM_MSG_USE" = 'MPI' ] && OM_P_MPI="OM_MSG_USE=MPI" || OM_P_MPI=

# push into ompp root and make log directory if not exist

if [ ! -d ompp ]; then
  echo ERROR: missing source code directory: ompp
  exit 1
fi

pushd ompp
OM_ROOT=$PWD

if [ ! -d log ]; then mkdir log; fi

# log build environment

echo Log file: log/build-models.log
echo `date` Build openM++ models | tee log/build-models.log
echo Environment: | tee -a log/build-models.log
echo " OM_BUILD_CONFIGS   = $OM_BUILD_CONFIGS" | tee -a log/build-models.log
echo " OM_MSG_USE         = $OM_MSG_USE" | tee -a log/build-models.log
echo " OM_ROOT            = $OM_ROOT" | tee -a log/build-models.log
echo " MODEL_DIRS         = $MODEL_DIRS" | tee -a log/build-models.log
echo Build configurations: $OM_BLD_CFG | tee -a log/build-models.log
if [ -z "$OM_P_MPI" ]; then
  echo Build desktop version: non-MPI | tee -a log/build-models.log
else
  echo Build cluster version: using MPI | tee -a log/build-models.log
fi;

# if OMPP_CPP_BUILD_TAG or OMPP_BUILD_TAG is set then build from that git tag

if [ -n "$OMPP_BUILD_TAG" ]; then
  OM_BLD_TAG="$OMPP_BUILD_TAG"
  echo " OMPP_BUILD_TAG     = $OMPP_BUILD_TAG" | tee -a log/build-models.log
fi
if [ -n "$OMPP_CPP_BUILD_TAG" ]; then
  OM_BLD_TAG="$OMPP_CPP_BUILD_TAG"
  echo " OMPP_CPP_BUILD_TAG = $OMPP_CPP_BUILD_TAG" | tee -a log/build-models.log
fi

if [ -n "$OM_BLD_TAG" ]; then

  echo "git checkout $OM_BLD_TAG"

  if ! git checkout "$OM_BLD_TAG" >> log/build-models.log 2>&1;
  then
    echo FAILED git checkout "$OM_BLD_TAG" | tee -a log/build-models.log
    exit 1
  fi
fi

# build models

pushd models

export MODEL_INI="${OM_ROOT}/../model.ini"
export MODEL_DIRS="${OM_BLD_MDLS//,/ }"

for C in ${OM_BLD_CFG//,/ }; do

  [ "$C" = 'RELEASE' ] && OM_P_RLS="RELEASE=1" || OM_P_RLS=

  echo make $OM_P_RLS $OM_P_MPI all publish run

  if ! make $OM_P_RLS $OM_P_MPI all publish run >> ../log/build-models.log 2>&1;
  then
    echo FAILED: make $OM_P_RLS $OM_P_MPI all publish run | tee -a ../log/build-models.log
    exit 1
  fi
done

# publish models into models/bin

echo make $OM_P_RLS $OM_P_MPI publish-all

if ! make $OM_P_RLS $OM_P_MPI publish-all >> ../log/build-models.log 2>&1;
then
  echo FAILED: make $OM_P_RLS $OM_P_MPI publish-all | tee -a ../log/build-models.log
  exit 1
fi

popd

echo `date` Done. | tee -a log/build-models.log
popd
