#!/usr/bin/env bash
#
# make new version of openMpp R package:
#   R CMD build openMpp

# push into ompp-make-r root and make log directory if not exist

if [ ! -d ompp-make-r ]; then 

  echo mkdir ompp-make-r
  
  if ! mkdir ompp-make-r; then
    echo FAILED
    exit 1
  fi
fi

pushd ompp-make-r

if [ ! -d log ]; then mkdir log; fi

LOG_DIR=$PWD/log
LOG_PATH=$LOG_DIR/make-r.log

# log build environment 

echo Log file: $LOG_PATH
echo `date` Build openMpp R package | tee $LOG_PATH

# get source code from git, if directory not already exist

if [ ! -d ompp-r ]; then
  
  echo git clone https://github.com/openmpp/R ompp-r | tee -a $LOG_PATH
  
  if ! git clone https://github.com/openmpp/R ompp-r >> $LOG_PATH 2>&1;
  then
    echo FAILED git clone | tee -a $LOG_PATH
    exit 1
  fi
else
  echo Skip: git clone
fi

# build openMpp R package

pushd ompp-r

echo R CMD build openMpp | tee -a $LOG_PATH

if ! R CMD build openMpp >> $LOG_PATH 2>&1;
then
  echo FAILED | tee -a $LOG_PATH
  exit 1
fi

popd

echo `date` Done. | tee -a $LOG_PATH
popd
