double qnorm5(double p, double mu, double sigma, int lower_tail, int log_p); /* Borrowed from R*/
double pnorm5(double x, double mu, double sigma, int lower_tail, int log_p); /* Borrowed from R*/
double qbeta(double alpha, double p, double q, int lower_tail, int log_p);/* Borrowed from R*/
double pbeta(double x, double pin, double qin, int lower_tail, int log_p);/* Borrowed from R*/
double pgamma(double x, double alpha, double scale, int lower_tail, int log_p);/* Borrowed from R*/
double qgamma(double p, double alpha, double scale, int lower_tail, int log_p);/* Borrowed from R*/

