; Complete example of ini-file located at: props/model/ompp/Model-example.ini

[OpenM]
SubValues = 1
Threads = 1

; [Parameter]
; SimulationCases = 5

; [Microdata]
; ToCsv = yes
; Person = lifespan_age, calendar_year, report_calendar_year, dementia
